version: '2'

services:
  mysql:
    image: 'bitnami/mysql:5.7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=my_database
      - MYSQL_PASSWORD=my_password
    volumes:
        - ./mysqldb:/var/lib/mysql
  myapp:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: clarkchan/laravel
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./workspace:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
